# from selenium.webdriver.common.by import By
# from selenium import webdriver
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("https://practice.automationtesting.in/")
# driver.implicitly_wait(15)
# driver.execute_script("window.scrollBy(0, 600);")
# selenium_ruby_ntn = driver.find_element(By.CSS_SELECTOR, "[alt='Selenium Ruby']")
# selenium_ruby_ntn.click()
# reviews_btn = driver.find_element(By.CSS_SELECTOR, "[href='#tab-reviews']")
# reviews_btn.click()
# five_stars_btn = driver.find_element_by_class_name("star-5")
# five_stars_btn.click()
# review = driver.find_element_by_id("comment")
# review.send_keys("Nice book!")
# name = driver.find_element_by_id("author")
# name.send_keys("Sveta")
# email = driver.find_element_by_id("email")
# email.send_keys("SvetaTester92@yandex.ru")
# submit_btn = driver.find_element_by_id("submit")
# submit_btn.click()
# driver.quit()
